#!/usr/bin/env python3
"""Regenerate crews/members.json from the desk's sectors.yaml and roles.yaml.

members.json is a build product. The six standing roles are fixed; everything
below them is generated by crossing two config files -- sectors.yaml says how many
pods there are and what each covers, roles.yaml says what a pod is made of. Every
pod gets a line manager plus one row per role. Generating them removes the only
real drift risk: near-identical hand-typed entries whose ticker lists go stale the
moment a ticker moves pods.

Nothing about the team composition lives in this file. Cut the debate roles, add a
macro hedger, drop the analysts from four to two -- edit roles.yaml and re-run.

Both files are looked up in $DESK_ROOT first (that tree is your data), and fall
back to this repository's config/*.example.yaml so a fresh clone runs.

An IC is spawned per ticker per round and has no standing session, so its row
carries no ``slot_hint``; ``artifact_globs`` and ``per_ticker`` say which files
it writes, and the backend folds its state from those. That table mirrors the
stage table in ``scripts/desk_events.py``.

Duty copy is an outward-facing job description: what this member does for the
reader. Never put orchestration internals in it (sentinel strings, tool or command
names, session mechanics) -- that is prompt material, not UI copy.

Usage:
    python3 crews/gen_members.py            # write crews/members.json
    python3 crews/gen_members.py --check    # exit 1 if the committed file is stale
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

APP_ROOT = Path(__file__).resolve().parent.parent
DESK_ROOT = Path(os.environ.get("DESK_ROOT") or Path.home() / "trading-desk")
OUT_PATH = Path(__file__).resolve().parent / "members.json"

#: Config lookup: the desk root wins, the shipped example is the fallback. Two
#: entries rather than one so a clone with no desk root still generates a roster
#: -- which is what lets the test suite run before anyone has a desk.
CONFIG_SOURCES = {
    "sectors": (DESK_ROOT / "sectors.yaml", APP_ROOT / "config" / "sectors.example.yaml"),
    "roles": (DESK_ROOT / "roles.yaml", APP_ROOT / "config" / "roles.example.yaml"),
    "books": (DESK_ROOT / "books.yaml", APP_ROOT / "config" / "books.example.yaml"),
}

# --- duty copy (v6, finalized) ----------------------------------------------

# --- duty copy for the standing roles ---------------------------------------
#
# The six roles above the pods are fixed -- they are the chain of command, not a
# team composition, so they are written here rather than in config.
#
# Written in ENGLISH, like every ``title``. Duty is the outward-facing job
# description a reader sees, and the app displays it as stored -- it is not run
# through the language map, so whichever language you write here is the one both
# halves of your readers get. Rewrite these in your own language if your desk is
# read in one.
#
# The line-manager duty is a TEMPLATE: pod and tickers are substituted at render
# time, and ``duty_template`` travels with the row so the backend can re-render it
# when a ticker moves pods.

DUTY_FUND = (
    "Runs the desk day to day. Takes an instruction, orders the macro brief and "
    "the pods' research, follows it to completion, and comes back with one short "
    "report plus whatever needs a decision."
)
DUTY_MACRO = (
    "Calls the market environment before the open and suggests each pod's posture. "
    "Covers index, volatility, the dollar, rates, gold, oil and crypto -- never a "
    "single name."
)
DUTY_DESK_TEMPLATE = (
    "Runs research across {pod_count} sector pods. Starts them, tracks progress, "
    "and once all are in, folds their conclusions into a one-page brief with the "
    "opportunities ranked by conviction and payoff."
)
DUTY_RISK = (
    "Portfolio-level risk. Takes the pods' conclusions and the live book, measures "
    "exposure, concentration and tail risk, and proposes hedges. Flags risk; never "
    "recommends a trade."
)
DUTY_TRADER = (
    "Places the orders. Nothing is executed until you have approved it."
)
DUTY_SCRUM = (
    "Runs the morning standup and the post-close review, and keeps the team's "
    "delivery cadence honest."
)
# An engineering agent that maintains the desk itself is deliberately NOT a member:
# it sits outside the trading decision chain, and it neither analyzes a ticker nor
# places an order. Drawing it under the fund manager would read as a research or
# execution report line, which it is not.
DUTY_LINE_TEMPLATE = (
    "Owns the {pod} pod ({tickers}). Has the analysts research it independently, "
    "chairs the bull/bear debate and the risk review, and delivers this pod's "
    "conclusion on every ticker it covers."
)

# --- the IC layer -----------------------------------------------------------
#
# Read from roles.yaml, not written here. That file is the entry point for
# composing a team: the roles it lists are the rows every pod gets, in the order
# it lists them.
#
# Each role is spawned per ticker per round rather than kept as a standing
# session, so an IC row carries no ``slot_hint``: its state is folded from the
# artifacts it writes. ``artifacts`` and ``per_ticker`` mirror the stage table in
# ``scripts/desk_events.py``; ``per_ticker: ~`` means "scale with the pod's
# analyst_copies".
#
# ``title`` is required to be ENGLISH, like the six standing roles' -- the display
# language is mapped in ``ui/i18n.mjs`` (``memberTitle``), which is what makes the
# app's language switch reach these rows. A title stored here in another language
# survives the switch and prints the wrong language to the other half of the
# readers.


class ConfigProblem(Exception):
    """A config file is missing or malformed. Reported, never guessed around."""


def _config_path(kind: str) -> Path:
    """The file to read for ``kind``: the desk root's, else the shipped example."""
    primary, fallback = CONFIG_SOURCES[kind]
    if primary.is_file():
        return primary
    if fallback.is_file():
        return fallback
    raise ConfigProblem(
        f"no {kind} config: looked for {primary} then {fallback}"
    )


def _load_mapping(kind: str) -> dict:
    path = _config_path(kind)
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ConfigProblem(f"{path}: not valid YAML -- {exc}") from exc
    if not isinstance(data, dict):
        raise ConfigProblem(f"{path}: top level must be a mapping")
    return data


#: Every field a role must supply. Validated on load rather than at render time,
#: so a typo names the file and the row instead of raising a KeyError deep inside
#: the builder.
_ROLE_FIELDS = ("role", "title", "letter", "agent", "duty", "artifacts")


def load_roles() -> tuple[dict, ...]:
    """The IC roles, in file order, validated."""
    path = _config_path("roles")
    raw = _load_mapping("roles").get("roles")
    if not isinstance(raw, list) or not raw:
        raise ConfigProblem(f"{path}: needs a non-empty 'roles' list")
    roles: list[dict] = []
    seen: set[str] = set()
    for index, entry in enumerate(raw):
        at = f"{path}: roles[{index}]"
        if not isinstance(entry, dict):
            raise ConfigProblem(f"{at} must be a mapping")
        missing = [f for f in _ROLE_FIELDS if not entry.get(f)]
        if missing:
            raise ConfigProblem(f"{at} is missing {', '.join(missing)}")
        role = str(entry["role"])
        if not role.replace("-", "").isalnum() or not role.islower():
            raise ConfigProblem(
                f"{at}: role {role!r} must be lowercase letters, digits and dashes "
                "-- it becomes part of the member id"
            )
        if role in seen:
            raise ConfigProblem(f"{at}: duplicate role {role!r}")
        seen.add(role)
        artifacts = entry["artifacts"]
        if not isinstance(artifacts, list) or not all(artifacts):
            raise ConfigProblem(f"{at}: artifacts must be a non-empty list of globs")
        per_ticker = entry.get("per_ticker")
        if per_ticker is not None and not (isinstance(per_ticker, int) and per_ticker > 0):
            raise ConfigProblem(
                f"{at}: per_ticker must be a positive integer or null "
                "(null = scale with the pod's analyst_copies)"
            )
        roles.append({
            "role": role,
            "title": str(entry["title"]),
            "letter": str(entry["letter"]),
            "agent": str(entry["agent"]),
            "duty": " ".join(str(entry["duty"]).split()),
            "globs": [str(g) for g in artifacts],
            "per_ticker": per_ticker,
        })
    return tuple(roles)


def load_book_labels() -> dict[str, str]:
    """``{book id: display label}`` from books.yaml, empty when there is none.

    Optional on purpose: a desk with no books.yaml still generates a roster, its
    pod rows just fall back to the book id.
    """
    try:
        raw = _load_mapping("books").get("books")
    except ConfigProblem:
        return {}
    if not isinstance(raw, dict):
        return {}
    out: dict[str, str] = {}
    for key, cfg in raw.items():
        label = (cfg or {}).get("label") if isinstance(cfg, dict) else None
        out[str(key)] = str(label) if label else str(key)
    return out


def load_pods() -> list[tuple[str, list[str], str]]:
    """Pods in sectors.yaml order: ``(pod, tickers, book)``.

    ``book`` names the entry in books.yaml this pod trades against. It is carried
    here because the org chart labels a pod row with it, and a label composed from
    a fixed string would claim every pod trades the same book.
    """
    pods = _load_mapping("sectors").get("sectors") or {}
    out: list[tuple[str, list[str], str]] = []
    for pod, cfg in pods.items():
        cfg = cfg or {}
        out.append((
            str(pod),
            [str(t) for t in (cfg.get("tickers") or [])],
            str(cfg.get("book") or ""),
        ))
    return out


def build(pods: list[tuple[str, list[str], str]], roles: tuple[dict, ...]) -> dict:
    pod_count = len(pods)
    members: list[dict] = [
        {
            "id": "fund",
            "name": "fund-manager",
            "alias": "fund@",
            "title": "Fund Manager",
            "avatar_letter": "F",
            "duty": DUTY_FUND,
            "parent": None,
            "group": None,
            "pod": None,
            "tickers": [],
            "reports_label": "5",
            "agent": "tada-fund-manager",
            "slot_hint": {"folder": "Trading Desk", "title": "fund-manager"},
            "output_sources": [{"label": "report", "dir": "memory/briefs"}],
        },
        {
            "id": "macro",
            "name": "macro-strategist",
            "alias": "macro@",
            "title": "Macro Strategist",
            "avatar_letter": "M",
            "duty": DUTY_MACRO,
            "parent": "fund",
            "group": None,
            "pod": None,
            "tickers": [],
            "reports_label": "0",
            "agent": "tada-macro-strategist",
            "slot_hint": {"folder": "Trading Desk", "title": "macro-strategist"},
            "output_sources": [{"label": "macro brief", "dir": "teams/macro/reports"}],
        },
        {
            "id": "desk",
            "name": "desk-manager",
            "alias": "desk@",
            "title": "Desk Manager",
            "avatar_letter": "D",
            "duty": DUTY_DESK_TEMPLATE.format(pod_count=pod_count),
            "duty_template": DUTY_DESK_TEMPLATE,
            "parent": "fund",
            "group": None,
            "pod": None,
            "tickers": [],
            "reports_label": str(pod_count),
            "agent": "tada-desk-manager",
            "slot_hint": {"folder": "Trading Desk/Desk", "title": "desk-manager"},
            "output_sources": [{"label": "desk brief", "dir": "memory/briefs"}],
        },
        {
            "id": "risk",
            "name": "risk-pod",
            "alias": "risk@",
            "title": "Portfolio Risk",
            "avatar_letter": "R",
            "duty": DUTY_RISK,
            "parent": "fund",
            "group": None,
            "pod": None,
            "tickers": [],
            "reports_label": "0",
            "agent": "tada-risk-pod",
            "slot_hint": {"folder": "Trading Desk", "title": "risk-pod"},
            "output_sources": [{"label": "risk report", "dir": "portfolio/risk"}],
        },
        {
            "id": "trader",
            "name": "trader",
            "alias": "trader@",
            "title": "Trader",
            "avatar_letter": "T",
            "duty": DUTY_TRADER,
            "parent": "fund",
            "group": None,
            "pod": None,
            "tickers": [],
            "reports_label": "0",
            "agent": "tada-trader",
            "slot_hint": {"folder": "Trading Desk", "title": "trader"},
            "output_sources": [{"label": "fills", "dir": "portfolio"}],
        },
        {
            "id": "scrum",
            "name": "scrum-master",
            "alias": "scrum@",
            "title": "Scrum Master",
            "avatar_letter": "S",
            "duty": DUTY_SCRUM,
            "parent": "fund",
            "group": None,
            "pod": None,
            "tickers": [],
            "reports_label": "0",
            "agent": "tada-scrum-master",
            "slot_hint": {"folder": "Trading Desk", "title": "scrum-master"},
            "output_sources": [],
        },
    ]

    book_labels = load_book_labels()

    for pod, tickers, book in pods:
        # The pod row's label. Composed from the pod's OWN book rather than a fixed
        # string, and with no language-specific word in it -- the UI appends the
        # localized "pod" suffix, so a suffix baked in here would survive the
        # language switch.
        label = book_labels.get(book, book)
        group = f"{label} · {pod}" if label else str(pod)
        members.append(
            {
                "id": f"lm-{pod}",
                "name": f"line-manager · {pod}",
                "alias": f"{pod}@",
                "title": "Line Manager",
                "avatar_letter": "L",
                "duty": DUTY_LINE_TEMPLATE.format(pod=pod, tickers=" ".join(tickers)),
                "duty_template": DUTY_LINE_TEMPLATE,
                "parent": "desk",
                "group": group,
                "pod": pod,
                "tickers": tickers,
                "reports_label": str(len(roles)),
                "agent": "tada-line-manager",
                "slot_hint": {
                    "folder": f"Trading Desk/Desk/{pod}",
                    "title": f"line-manager · {pod}",
                },
                "output_sources": [
                    {"label": "pod report", "dir": f"teams/{pod}/reports"}
                ],
            }
        )
        for spec in roles:
            role = spec["role"]
            members.append(
                {
                    "id": f"ic-{pod}-{role}",
                    "name": f"{role} · {pod}",
                    # `<role>@<pod>` rather than a bare `<role>@`: every pod draws
                    # the same roles, so the pod is what makes the handle address
                    # one person instead of one per pod.
                    "alias": f"{role}@{pod}",
                    "title": spec["title"],
                    "avatar_letter": spec["letter"],
                    "duty": spec["duty"],
                    "parent": f"lm-{pod}",
                    "group": group,
                    "pod": pod,
                    # Tickers stay on the line-manager: an IC works every ticker
                    # in the pod, so repeating the list on every role row would say
                    # nothing the parent row does not already say.
                    "tickers": [],
                    "reports_label": "0",
                    "agent": spec["agent"],
                    # No slot_hint: spawned per ticker per round, never standing.
                    "artifact_globs": list(spec["globs"]),
                    "per_ticker": spec["per_ticker"],
                    "output_sources": [],
                }
            )

    return {
        "version": 1,
        "generated_by": "crews/gen_members.py",
        # NAMES, not paths: this file is committed, and an absolute path would make
        # --check fail on every machine but the one that generated it.
        "sources": ["sectors.yaml", "roles.yaml"],
        "members": members,
    }


def render(doc: dict) -> str:
    return json.dumps(doc, ensure_ascii=False, indent=2) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if members.json differs from generator output",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=OUT_PATH,
        help="write the roster to this path (default: crews/members.json). Point it at a "
        "temp path with DESK_ROOT set to generate a roster for another desk without "
        "touching the committed file. Ignored by --check, which always compares the "
        "committed crews/members.json.",
    )
    args = ap.parse_args()

    try:
        doc = build(load_pods(), load_roles())
    except ConfigProblem as exc:
        print(f"config error: {exc}", file=sys.stderr)
        return 2
    text = render(doc)
    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current != text:
            print(f"STALE: {OUT_PATH} differs from generator output", file=sys.stderr)
            return 1
        print(f"OK: {OUT_PATH} matches {_config_path('sectors')} + {_config_path('roles')}")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(json.loads(text)['members'])} members)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
