#!/usr/bin/env python3
"""Seed a self-contained, entirely fictional demo desk root.

The fixtures under ``fixtures/`` are DERIVED from a desk tree on disk (see
``fixtures/gen_fixtures.py``). The real desk that tree once described is private
data and is not in this repository, so this script builds a synthetic stand-in:
a complete desk root whose config is the shipped example and whose artifacts are
obviously made-up placeholders. Point ``gen_fixtures.py`` at the result and the
shared mock data regenerates with nothing real in it.

    python3 scripts/seed_demo_desk.py "$KIROCREW_SCRATCH/demo-desk"
    DESK_ROOT="$KIROCREW_SCRATCH/demo-desk" python3 fixtures/gen_fixtures.py

What it writes, under the target directory:

* ``sectors.yaml`` -- the pods and tickers from ``config/sectors.example.yaml``,
  with a ``line_manager`` on each pod so the tree is a valid desk root.
* ``books.yaml``, ``roles.yaml`` -- copied from the shipped examples.
* ``engine/validate_config.py`` -- copied from ``config/engine``.
* dated artifacts for every pod and ticker in the config: a CEO brief, a macro /
  desk / risk report, one rollup per pod, and one file per role per ticker
  matching the ``artifacts`` globs in ``roles.yaml``.
* an empty ``runs/``.

Every markdown body is a couple of neutral, plainly fictional sentences: no price
target, no figure, no recommendation. The script is idempotent -- a second run
rewrites the same bytes -- and refuses to write into a directory that already
holds a ``portfolio/`` or a non-empty ``teams/`` unless ``--force`` is given, so
it can never be aimed at a real desk by mistake.
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG = REPO_ROOT / "config"
GEN_FIXTURES = REPO_ROOT / "fixtures" / "gen_fixtures.py"

#: Standing reports the desk layer writes outside a pod (§2 data sources).
STANDING_REPORT_TEAMS = ("macro", "desk", "risk-pod")

#: Fallback if the date cannot be read out of gen_fixtures.py.
_FALLBACK_DATE = "2026-09-07"


def default_date() -> str:
    """The date ``gen_fixtures.py`` cuts fixtures for, read from its source.

    Parsed rather than imported: importing that module would run its generation
    against whatever ``DESK_ROOT`` points at as a side effect.
    """
    try:
        text = GEN_FIXTURES.read_text(encoding="utf-8")
    except OSError:
        return _FALLBACK_DATE
    match = re.search(r'^RUN_DATE\s*=\s*"(\d{4}-\d{2}-\d{2})"', text, re.MULTILINE)
    return match.group(1) if match else _FALLBACK_DATE


# --------------------------------------------------------------------------- #
# safety
# --------------------------------------------------------------------------- #

def looks_like_a_real_desk(target: Path) -> str | None:
    """A reason to refuse, or None. Guards against pointing this at real data."""
    if (target / "portfolio").exists():
        return f"{target} has a portfolio/ -- refusing (looks like a real desk)"
    teams = target / "teams"
    if teams.is_dir() and any(teams.iterdir()):
        return f"{target} has a non-empty teams/ -- refusing (looks like a real desk)"
    return None


# --------------------------------------------------------------------------- #
# config
# --------------------------------------------------------------------------- #

def write_config(target: Path) -> tuple[dict, list[dict]]:
    """Write the four config files and return (sectors mapping, roles list)."""
    example_sectors = yaml.safe_load(
        (CONFIG / "sectors.example.yaml").read_text(encoding="utf-8")
    )
    pods = example_sectors.get("sectors") or {}
    # A desk-root sectors.yaml carries a line_manager per pod; the shipped
    # example omits it. Add it so the tree validates as a real desk root.
    for cfg in pods.values():
        if isinstance(cfg, dict):
            cfg.setdefault("line_manager", "line-manager")

    header = (
        "# Demo desk root -- synthetic, generated by scripts/seed_demo_desk.py.\n"
        "# Pods and tickers are the shipped example; nothing here is a real position.\n\n"
    )
    _write(
        target / "sectors.yaml",
        header + yaml.safe_dump(example_sectors, sort_keys=False, allow_unicode=False),
    )

    # books.yaml, roles.yaml and the validator are the shipped examples verbatim.
    shutil.copyfile(CONFIG / "books.example.yaml", target / "books.yaml")
    shutil.copyfile(CONFIG / "roles.example.yaml", target / "roles.yaml")
    (target / "engine").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(
        CONFIG / "engine" / "validate_config.py",
        target / "engine" / "validate_config.py",
    )

    roles = yaml.safe_load((target / "roles.yaml").read_text(encoding="utf-8"))["roles"]
    return pods, roles


# --------------------------------------------------------------------------- #
# artifacts
# --------------------------------------------------------------------------- #

def _brief_body(kind: str) -> str:
    return (
        f"# {kind} (demo)\n\n"
        "Synthetic placeholder content for the demo desk. It stands in for a real "
        "daily write-up so the app has something to render. It names no real "
        "position and makes no recommendation.\n"
    )


def _analyst_body(role: str, ticker: str) -> str:
    return (
        f"# {role} note - {ticker} (demo)\n\n"
        f"Synthetic placeholder analysis for {ticker}. The desk uses this only to "
        "exercise the artifact tree. It reflects no real research and reaches no "
        "conclusion.\n"
    )


def _role_files(glob: str, count: int) -> list[str]:
    """Filenames a role owes per ticker, expanding a ``*`` copy glob."""
    if "*" in glob:
        return [glob.replace("*", str(i)) for i in range(1, count + 1)]
    return [glob]


def write_artifacts(target: Path, pods: dict, roles: list[dict], date: str) -> int:
    """Write every dated artifact. Returns the count of markdown files written."""
    written = 0

    _write(target / "memory" / "briefs" / f"{date}.md", _brief_body("Desk brief"))
    written += 1
    for team in STANDING_REPORT_TEAMS:
        _write(
            target / "teams" / team / "reports" / f"{date}.md",
            _brief_body(f"{team} report"),
        )
        written += 1

    for pod, cfg in pods.items():
        cfg = cfg or {}
        tickers = [str(t) for t in (cfg.get("tickers") or [])]
        copies = int(cfg.get("analyst_copies", 1) or 1)
        _write(
            target / "teams" / pod / "reports" / f"{date}.md",
            _brief_body(f"{pod} report"),
        )
        written += 1
        for ticker in tickers:
            tdir = target / "teams" / pod / "reports" / date / ticker
            for role in roles:
                per = role.get("per_ticker")
                count = per if isinstance(per, int) and per > 0 else copies
                for glob in role["artifacts"]:
                    for name in _role_files(str(glob), count):
                        _write(tdir / name, _analyst_body(str(role["role"]), ticker))
                        written += 1

    (target / "runs").mkdir(parents=True, exist_ok=True)
    return written


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


# --------------------------------------------------------------------------- #
# cli
# --------------------------------------------------------------------------- #

def seed(target: Path, date: str, force: bool) -> int:
    if not force:
        reason = looks_like_a_real_desk(target)
        if reason:
            print(f"error: {reason}. Pass --force to override.", file=sys.stderr)
            return 2

    target.mkdir(parents=True, exist_ok=True)
    pods, roles = write_config(target)
    count = write_artifacts(target, pods, roles, date)
    pod_names = ", ".join(pods) or "(none)"
    print(f"seeded demo desk at {target}")
    print(f"  date {date} · pods: {pod_names} · {count} markdown artifacts")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("target", type=Path, help="directory to seed the demo desk into")
    parser.add_argument(
        "--date",
        default=default_date(),
        help="run date for the dated artifacts (default: the date gen_fixtures.py uses)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="write even if the target already looks like a desk (portfolio/ or non-empty teams/)",
    )
    args = parser.parse_args(argv)

    if not re.match(r"^\d{4}-\d{2}-\d{2}$", args.date):
        parser.error(f"--date must be YYYY-MM-DD, got {args.date!r}")
    return seed(args.target, args.date, args.force)


if __name__ == "__main__":
    raise SystemExit(main())
